# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c13e766351f322f02102d8c3d886966d6e36adf08aa3be6a1f92363b2fa6a01504cfb03b6828df2f46f25c47ea01863f8a36596f1e05430da5712119b152ebaf

test:
  secret_key_base: 23d6b7f03a3fd9a99475f3f513ed7c1c71d0b80738098bb15868720c1845399e441fa196113dd850d4f000cc5093a914c528330bcc603f9c6da5df99bda7e5f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
